catalog:
  '@antfu/eslint-config': ^6.0.0
  '@eslint-react/eslint-plugin': ^2.3.1
  '@eslint/js': ^9.34.0
  '@graphiql/plugin-explorer': ^5.1.1
  '@graphiql/toolkit': ^0.11.3
  '@types/eslint-plugin-jsx-a11y': ^6.10.0
  '@types/react': ^19.1.12
  '@types/react-dom': ^19.1.9
  '@vitejs/plugin-react-swc': ^4.0.1
  eslint: ^9.39.1
  eslint-plugin-format: ^1.0.2
  eslint-plugin-jsx-a11y: ^6.10.2
  eslint-plugin-react-hooks: ^7.0.1
  eslint-plugin-react-refresh: ^0.4.24
  globals: ^16.3.0
  graphiql: ^5.2.1
  graphql: ^15.0.0
  graphql-ws: ^6.0.6
  react: ^19.1.1
  react-dom: ^19.1.1
  sass-embedded: ^1.93.3
  typescript: ^5.9.3
  typescript-eslint: ^8.41.0
  vite: ^7.1.3
onlyBuiltDependencies:
  - '@swc/core'
  - esbuild
